In [3]:
% matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import msmtools.generation as msmgen
import pyemma.msm as msm

In [4]:
import pyemma
from numpy import *

In [5]:
M = array([[0.9,0.1],[0.1,0.9]])
M

array([[ 0.9,  0.1],
       [ 0.1,  0.9]])

######  Compute coarse grained stationary probability of a process given its transition matrix M

In [6]:
pyemma.msm.PCCA(M, 2).coarse_grained_stationary_probability

array([ 0.5,  0.5])

##### Compute the coarse grained transition matrix

In [7]:
pyemma.msm.PCCA(M, 2).coarse_grained_transition_matrix

array([[ 0.9,  0.1],
       [ 0.1,  0.9]])

###### Compute the membership functions

In [8]:
pyemma.msm.PCCA(M, 2).memberships

array([[ 1.,  0.],
       [ 0.,  1.]])

In [9]:
pyemma.msm.PCCA(M, 2).metastable_assignment

array([0, 1], dtype=int64)

In [10]:
pyemma.msm.PCCA(M, 2).metastable_sets

[array([0], dtype=int64), array([1], dtype=int64)]

##### Number of metastable sets

In [11]:
pyemma.msm.PCCA(M, 2).n_metastable

2

In [12]:
pyemma.msm.PCCA(M, 2).output_probabilities

array([[ 1.,  0.],
       [ 0.,  1.]])

##### Stationary probability

In [13]:
pyemma.msm.PCCA(M, 2).stationary_probability

array([ 0.5,  0.5])

##### Transition matrix

In [14]:
pyemma.msm.PCCA(M, 2).transition_matrix

array([[ 0.9,  0.1],
       [ 0.1,  0.9]])